version: '3.1'

services:
  hello:
    build:
      context: ./hello # 构建镜像的文件路径, . 当前目录
      dockerfile: Dockerfile  # 构建镜像的文件名称
    container_name: hello
    restart: always
    privileged: true
    environment:
      - 'TZ="Asia/Shanghai"'  # 设置为中国时区
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - default
      - app_net

networks:
  app_net:   # 连接外部网络app_net
    external: true